name: Export Scene Test

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:
    inputs:
      testCase:
        description: "specify a case to run"
        default: "*"
        required: false


jobs:
    export-scene-test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Go
          uses: actions/setup-go@v5
          with:
            go-version-file: './go.mod'

        - name: Cache Dependencies
          uses: actions/cache@v4
          with:
            path: ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ matrix.golang }}-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-${{ matrix.golang }}-

        - name: Run tests
          run: |
            echo "${{ secrets.TEST_CONFIG }}"
            echo ${{ github.event.inputs.testCase }}
            if [ ${{ github.event.inputs.testCase }} == "" ]; then
              go test -v sceneTest/export/export_test.go -cid 10501083436840068643 -config ${{ secrets.TEST_CONFIG }}
            else
              go test -v sceneTest/export/export_test.go -cid 10501083436840068643 -config ${{ secrets.TEST_CONFIG }} -run ${{ github.event.inputs.testCase }}
            fi
            
             if [[ "$exitcode" != "0" ]]
